INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 09:20:20] "[33mGET / HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 09:20:20] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:01:44] "POST /auth/register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:01:44] "POST /auth/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:01:44] "[31m[1mPOST /auth/logout HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:01:44] "[31m[1mPOST /auth/logout HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:01:44] "POST /auth/logout HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:01:44] "POST /auth/register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:01:44] "[31m[1mPOST /auth/login HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:01:44] "POST /auth/register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:01:44] "[31m[1mPOST /auth/login HTTP/1.1[0m" 401 -
ERROR:be.serve:Exception on /shutdown [GET]
Traceback (most recent call last):
  File "C:\Users\sun_e\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\sun_e\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\sun_e\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\sun_e\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\sun_e\Desktop\git_project\dbProject1\project1\bookstore\be\serve.py", line 23, in be_shutdown
    shutdown_server()
  File "C:\Users\sun_e\Desktop\git_project\dbProject1\project1\bookstore\be\serve.py", line 17, in shutdown_server
    raise RuntimeError("Not running with the Werkzeug Server")
RuntimeError: Not running with the Werkzeug Server
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:01:44] "[35m[1mGET /shutdown HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:03:14] "POST /auth/register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:03:14] "POST /auth/register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:03:14] "POST /auth/unregister HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:03:15] "POST /auth/register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:03:15] "[31m[1mPOST /auth/unregister HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:03:15] "[31m[1mPOST /auth/unregister HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:03:15] "POST /auth/register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:03:15] "[35m[1mPOST /auth/register HTTP/1.1[0m" 512 -
ERROR:be.serve:Exception on /shutdown [GET]
Traceback (most recent call last):
  File "C:\Users\sun_e\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\sun_e\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\sun_e\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\sun_e\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\sun_e\Desktop\git_project\dbProject1\project1\bookstore\be\serve.py", line 23, in be_shutdown
    shutdown_server()
  File "C:\Users\sun_e\Desktop\git_project\dbProject1\project1\bookstore\be\serve.py", line 17, in shutdown_server
    raise RuntimeError("Not running with the Werkzeug Server")
RuntimeError: Not running with the Werkzeug Server
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:03:15] "[35m[1mGET /shutdown HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:03:59] "POST /auth/register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:03:59] "POST /auth/password HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:03:59] "[31m[1mPOST /auth/login HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:04:00] "POST /auth/login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:04:00] "POST /auth/logout HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:04:00] "POST /auth/register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:04:00] "[31m[1mPOST /auth/password HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:04:00] "[31m[1mPOST /auth/login HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:04:00] "POST /auth/register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:04:00] "[31m[1mPOST /auth/password HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:04:00] "[31m[1mPOST /auth/login HTTP/1.1[0m" 401 -
ERROR:be.serve:Exception on /shutdown [GET]
Traceback (most recent call last):
  File "C:\Users\sun_e\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\sun_e\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\sun_e\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\sun_e\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\sun_e\Desktop\git_project\dbProject1\project1\bookstore\be\serve.py", line 23, in be_shutdown
    shutdown_server()
  File "C:\Users\sun_e\Desktop\git_project\dbProject1\project1\bookstore\be\serve.py", line 17, in shutdown_server
    raise RuntimeError("Not running with the Werkzeug Server")
RuntimeError: Not running with the Werkzeug Server
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:04:00] "[35m[1mGET /shutdown HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:06:59] "POST /auth/register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:06:59] "POST /auth/register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:06:59] "POST /auth/unregister HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:06:59] "POST /auth/register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:06:59] "[31m[1mPOST /auth/unregister HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:06:59] "[31m[1mPOST /auth/unregister HTTP/1.1[0m" 401 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:06:59] "POST /auth/register HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:06:59] "[35m[1mPOST /auth/register HTTP/1.1[0m" 512 -
ERROR:be.serve:Exception on /shutdown [GET]
Traceback (most recent call last):
  File "C:\Users\sun_e\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\sun_e\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\sun_e\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\sun_e\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\sun_e\Desktop\git_project\dbProject1\project1\bookstore\be\serve.py", line 23, in be_shutdown
    shutdown_server()
  File "C:\Users\sun_e\Desktop\git_project\dbProject1\project1\bookstore\be\serve.py", line 17, in shutdown_server
    raise RuntimeError("Not running with the Werkzeug Server")
RuntimeError: Not running with the Werkzeug Server
INFO:werkzeug:127.0.0.1 - - [24/Oct/2024 11:06:59] "[35m[1mGET /shutdown HTTP/1.1[0m" 500 -
